name: Publish Package to npmjs
on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@berg-layout'
      - run: yarn
      - run: yarn build
      - run: yarn publish-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
