name: Publish Package to npmjs
on:
  release:
    types: [published]
if: github.ref == 'refs/heads/main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@berg-layout'
      - run: yarn
      - run: yarn publish-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
