name: Publish Package to npmjs
on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          scope: '@berg-layout'
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish-lib
